#
# Copyright 2023 The OpenVEX Authors
# SPDX-License-Identifier: Apache-2.0
#

name: test-vexctl-action

on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:

  test_vexctl_action:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    permissions: {}
    name: Install vexctl and test presence in path
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - name: Install vexctl
        uses: ./
      - name: Check install!
        run: vexctl version
      - name: Check root directory
        run: |
          if [[ $(git diff --stat) != '' ]]; then
            echo 'should be clean'
            exit 1
          else
            exit 0
          fi
        shell: bash

  test_vexctl_action_custom_dir_root:
    runs-on: ubuntu-latest
    permissions: {}
    name: Install Custom vexctl and test presence in path with custom root dir
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - name: Install vexctl
        uses: ./
        with:
          install-dir: /usr/bin
          use-sudo: true
      - name: Check install!
        run: vexctl version
      - name: Check install dir!
        run: |
          [[ $(dirname "$(which vexctl)") == /usr/bin ]]
        shell: bash
      - name: Check root directory
        run: |
          [[ -z $(git diff --stat) ]]
        shell: bash

  test_vexctl_action_custom_dir:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    permissions: {}
    name: Install Custom path vexctl and test presence in path
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - name: Install vexctl
        uses: ./
        with:
          install-dir: "$HOME/.vexctltest"
      - name: Check install!
        run: vexctl version
      - name: Check install dir!
        run: |
          [[ $(dirname "$(which vexctl)") == "$HOME/.vexctltest" ]]
        shell: bash
      - name: Check root directory
        run: |
          [[ -z $(git diff --stat) ]]
        shell: bash

  test_vexctl_action_wrong:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    permissions: {}
    name: Try to install a wrong vexctl
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - name: Install vexctl
        uses: ./
        with:
          vexctl-release: 'honk'
        continue-on-error: true
